services:
  app:
    build: .
    container_name: auth
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=./internal/config/local.yaml
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=auth_password
      - POSTGRES_DB=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: auth_postgres
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: postgres
    ports:
      - "5436:5432"